# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f12b86451aabd0133ce10fb98814b972ea7041c00d2f3165bb0f07acb91660ac9b459a72de3aec128d3ba713b568c5ef9834a141582bc05f2232ecc61a0654

test:
  secret_key_base: 84a0cd91069513262eb856d9d43a0b81b7c865d664ef90caaefd3f4f7433f3d48d4f69842c98da309ee19777d82226ac27e664bf3e88a1970f89fd5cc532f71d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
